### ISSUE TITLE
关于新建项目（Windows）bug

### ISSUE THREAD

**Issue by lixiansky** [weixin/WeFlow#10]
### 在新建项目的时候如果不输入项目名称，然后再点击左下角的**+**号一直弹出提示输入项目名称，没有办法输入

![6mv 4 1kdeiv 3_ 4 v 81](https://cloud.githubusercontent.com/assets/6084064/16214758/2382cc12-378e-11e6-8871-630c5a1e5de2.png)

**Comment by littledu** [comment]
退出进程重来

**Comment by lixiansky** [comment]
@littledu 恩恩！！！
