### ISSUE TITLE
编译后dist文件内容不全

### ISSUE THREAD

**Issue by ElvaLiuY** [weixin/WeFlow#100]
#### 运行环境

- [x] 操作系统 & 版本：win7
- [x] WeFlow 版本： `v1.3.2

#### 反馈具体描述：

时常会出现编译后dist文件中内容不全，甚至有时就没有dist文件

**Comment by hzlzh** [comment]
尝试一下 Demo 能否运行正常，如果正常，看一下是不是某些语法写法导致的报错

**Comment by lilyneaoer** [comment]
@ElvaLiuY 我也遇到同样的问题了，后来解决了吗
