### ISSUE TITLE
怎么修改px2rem基准值 

### ISSUE THREAD

**Issue by 15697289437** [weixin/WeFlow#102]
怎么修改px2rem基准值

**Comment by littledu** [comment]
https://github.com/weixin/tmt-workflow/blob/master/project/src/css/lib/lib-rem.less

用的是这个文件，你可以在你自己的文件里面进行覆盖。

**Comment by 15697289437** [comment]
weflow打包编译pm2rem的基准值，看源码中是定死了20

**Comment by hzlzh** [comment]
参看这里：https://github.com/weixin/WeFlow/issues/77#issuecomment-249093731
