### ISSUE TITLE
请教：js压缩合并的问题

### ISSUE THREAD

**Issue by ipengyo** [weixin/WeFlow#104]
#### 运行环境

- [x] 操作系统 & 版本：macOS (10.x.x)
- [x] WeFlow 版本： `v1.3.2`

#### 反馈具体描述：

这项目还有人维护吗？？？

这么大的BUG居然没有人修！！

![image](https://cloud.githubusercontent.com/assets/9323722/24837528/ce7bda58-1d68-11e7-9b2e-193f7eec027b.png)

![image](https://cloud.githubusercontent.com/assets/9323722/24837531/d9e568a0-1d68-11e7-9548-891bfc3ca7ee.png)

早知道自己写脚本解决算了。。。。
我想问一下 这个工具不测试的吗？？？？？？？？？？？？？？？？

**Comment by littledu** [comment]
已着手修复，可以先使用 https://github.com/weixin/tmt-workflow 解决
