### ISSUE TITLE
定制需求后如何能打包成原来一样的dmg文件

### ISSUE THREAD

**Issue by zjz19901029** [weixin/WeFlow#105]
#### 运行环境

- [x] 操作系统 & 版本：`macOS (10.x.x)` / `Windows (7/8/10)`
- [x] WeFlow 版本： `v1.3.2`

#### 反馈具体描述：
想问下，我根据自己的项目需求，修改了源码后，怎么样能够将这些文件打包进你们安装包一样的dmg文件呢？是否有什么工具？

**Comment by hzlzh** [comment]
你可以参看这里打包编译，https://github.com/weixin/WeFlow/blob/master/.travis.yml
如果要制作 DMG 安装文件可以试试 [DMG-Canvas] (http://www.araelium.com/dmgcanvas)
