### ISSUE TITLE
编译挂掉

### ISSUE THREAD

**Issue by alucardxpmusic** [weixin/WeFlow#108]
#### 关于 Issues 的提交说明
编译卡死

__ 以上文本阅读后请删除 __

#### 运行环境

- [x] 操作系统 & 版本：Windows 7
- [x] WeFlow 版本： `v1.3.2`

**Comment by littledu** [comment]
如何个挂法？另外，目前最新是 1.3.3 哦

**Comment by alucardxpmusic** [comment]
大清早把 WeFlow-1.3.3-win32-x64.zip 下载下来，然后把原来的文件夹删除用这个替换了，点击开发没问题，点击开发右边的编译按钮就一直runing不动了，然后我重新降到之前的1.3.2版本就正常了，项目没有动，在桌面上，当时是用1.3.2生成的。

**Comment by littledu** [comment]
可以打开调试模式，看一下编译挂了的时候报错吗？

**Comment by alucardxpmusic** [comment]
C:\Users\Administrator\Desktop\WeFlow-win32-x64\resources\app\src\_tasks\dist.js:146 compileLess success.
C:\Users\Administrator\Desktop\WeFlow-win32-x64\resources\app\src\_tasks\dist.js:166 compileSass success.
C:\Users\Administrator\Desktop\WeFlow-win32-x64\resources\app\src\_tasks\dist.js:182 compileAutoprefixer success.
C:\Users\Administrator\Desktop\WeFlow-win32-x64\resources\app\src\_tasks\dist.js:200 miniCSS success.
C:\Users\Administrator\Desktop\WeFlow-win32-x64\resources\app\node_modules\weflow-imagemin\index.js:89 gulp-imagemin: Minified 0 images
C:\Users\Administrator\Desktop\WeFlow-win32-x64\resources\app\src\_tasks\dist.js:228 imageminSprite success.
C:\Users\Administrator\Desktop\WeFlow-win32-x64\resources\app\src\_tasks\dist.js:239 copyMedia success.
C:\Users\Administrator\Desktop\WeFlow-win32-x64\resources\app\src\_tasks\dist.js:401 miniSVG success.
events.js:154 Uncaught SyntaxError in plugin 'gulp-babel'
Message:
    C:/Users/Administrator/Desktop/wxad/20170614-promo-matt/src/js/main.js: Invalid number (31:18)
C:\Users\Administrator\Desktop\WeFlow-win32-x64\resources\app\node_modules\weflow-imagemin\index.js:89 gulp-imagemin: Minified 14 images (saved 11.9 kB - 4.3%)
C:\Users\Administrator\Desktop\WeFlow-win32-x64\resources\app\src\_tasks\dist.js:214 imageminImg success.

**Comment by littledu** [comment]
C:/Users/Administrator/Desktop/wxad/20170614-promo-matt/src/js/main.js: Invalid number (31:18)

你这行代码附近通不过 babel 的编译。

**Comment by alucardxpmusic** [comment]
嗯，我还是降回去用1.3.2版本，我那个用不到ES6的。麻烦了

**Comment by littledu** [comment]
没事，如果方便的话，可以把代码给我一份吗？我看下怎么兼容好。发到 410491325@qq.com

**Comment by alucardxpmusic** [comment]
要得哈，你顺便帮我看看微信广告里的 
wximg.qq.com/wxp/libs/wxmoment/0.0.4/wxmoment.min.js这个js里的微信分享功能也要扯拐，我是严格按照文档来的，是不是 WeixinJSBridge 调用分享接口挂掉了，那必须得引用 Weixin JS SDK 来分享接口了哇？

**Comment by littledu** [comment]
好的，麻烦了。

至于这里面的分享接口，是只能在 qq.com 域名下才行的，如果你的项目到时是在 qq 域名下，可以回头发布了再调一下，按照文档写就好了。而如果不是，你就要用 sdk 去自己实现分享了。

**Comment by alucardxpmusic** [comment]
明白了，tks。
