### ISSUE TITLE
windows版添加项目一直提示输入项目名称

### ISSUE THREAD

**Issue by maxlcoder** [weixin/WeFlow#18]
windows版添加项目一直提示输入项目名称windows版添加项目一直提示输入项目名称windows版添加项目一直提示输入项目名称windows版添加项目一直提示输入项目名称windows版添加项目一直提示输入项目名称windows版添加项目一直提示输入项目名称

**Comment by hzlzh** [comment]
这个问题新版已经解决，试试吧
