### ISSUE TITLE
weflow.io使用了沃通证书

### ISSUE THREAD

**Issue by evecalm** [weixin/WeFlow#2]
不知道有多少人和我一样，已经用工具吊销了所有中国流氓软件的证书以及一些不可信的的CA证书，沃通在其列，打开官网不太顺畅。

**Comment by hzlzh** [comment]
已经更换了CA，Enjoy!
![image](https://cloud.githubusercontent.com/assets/1049575/16169836/8180c92a-356f-11e6-9e82-8d492b9be260.png)
