### ISSUE TITLE
不理解为什么在windows 下编码~

### ISSUE THREAD

**Issue by epirus** [weixin/WeFlow#21]
不理解为什么在windows 下编码~后面会多出^M的字符~

**Comment by hzlzh** [comment]
能否发一份出现特殊字符的文件，方便问题定位。

**Comment by epirus** [comment]
不好意思我描述的不好~  就是在linux跟mac的环境下，如果使用vim进行浏览会出现^M的字符。这种字符是应为在windows中编写代码带来的~应该可以使用对应的编辑器去掉。


https://www.zhihu.com/question/22130727

**Comment by hzlzh** [comment]
![image](https://cloud.githubusercontent.com/assets/1049575/16408884/6787aa76-3d4d-11e6-8044-84b5bf25d96e.png)
你描述的问题应该就是编辑器设置的结尾换行符格式选取 win 还是 *nix 的问题，我们通常在 macOS 下的  Webstrom 编辑，少数文件会在 Windows 下提交，这个问题我们后面考虑一下做个统一，预计会选区 unix 或者 macOS 风格。
