### ISSUE TITLE
windows 1.2.1版本打开 无响应

### ISSUE THREAD

**Issue by mlzk** [weixin/WeFlow#23]
#### 运行环境

- [x] 操作系统 & 版本：windows7（64位）
- [x] WeFlow 版本： `v1.2.1`

#### 反馈具体描述：
打开weflow 点击按钮 均无响应，（然而1.2.0可以运行）；

![qr i vr7mvug1h wt7m5lz6](https://cloud.githubusercontent.com/assets/9440172/16410234/2271cae6-3d54-11e6-96a4-69ad066d5299.png)

**Comment by littledu** [comment]
试试今天刚发的 1.3.1 ？

**Comment by mlzk** [comment]
可以
