### ISSUE TITLE
src/css 多了一个.DS_Store文件

### ISSUE THREAD

**Issue by ouzhou** [weixin/WeFlow#24]
#### 运行环境

- [x] 操作系统 & 版本：`Windows (10)`  
- [x] WeFlow 版本： `v1.3.1`

#### 反馈具体描述：
src/css 多了一个.DS_Store文件 :)
虽然感觉不太重要

**Comment by littledu** [comment]
这是 macOS 的隐藏文件，不影响使用，已经清除
