### ISSUE TITLE
自动生成图片 CSS 属性，width & height 不成功，imagemin 图片压缩jpg压缩效果不太好

### ISSUE THREAD

**Issue by vfv** [weixin/WeFlow#25]
运行环境
Windows 10 64   WeFlow 版本： `v1.3.1`

自动生成图片 CSS 属性，width & height 不成功；
imagemin 图片压缩对png效果很好，jpg的压缩效果不太好，是否可以给个调整压缩质量的借口或选项

**Comment by hzlzh** [comment]
#### 1. 自动添加 width & height 这个会读取项目配置文件里的启用目录：

打开你的项目配置文件 `weflow.config.json`，追加 `lazyDir` 的参数来开启一下，WeFlow 下一版我们将默认打开。（via https://github.com/weixin/tmt-workflow/blob/master/.tmtworkflowrc#L35）

````json
{
    "ftp": {
        "host": "",
        "port": "",
        "user": "",
        "pass": "",
        "remotePath": "",
        "includeHtml": true
    },
    "livereload": true,
    "lazyDir": [
        "../slice"
    ],
    "supportREM": true,
    "supportWebp": false,
    "supportChanged": false,
    "reversion": false,
    "lazyDir": [
        "../slice",
        "../img"
    ]
}
````

#### 2. 关于图片压缩和压缩质量：

目前的 PNG 压缩质量是在效果和带宽中权衡之后的选择，非常多业务都在使用，所以没有提供质量选项。
JPG 建议是从设计稿输出的时候就压缩为最优，当然我们也会考虑在 GUI 界面提供更多图片相关的设置。

**Comment by vfv** [comment]
谢谢，好项目
