### ISSUE TITLE
 好像src/img下不能放svg

### ISSUE THREAD

**Issue by ouzhou** [weixin/WeFlow#26]
#### 运行环境

- [x] 操作系统 & 版本：`Windows (10)` 
- [x] WeFlow 版本： `v1.3.1`

#### 反馈具体描述：
svg文件不能放置在img目录中，求解决方法，现在是放置在media文件夹里面的

**Comment by littledu** [comment]
嗯，目前 `img` 目录的限制是： `JPG,jpg,png,gif`,  `media` 没任何限制。我记录一下，下一版把 svg 加进去
