### ISSUE TITLE
开发版node-sass依赖环境问题

### ISSUE THREAD

**Issue by lilijialiang** [weixin/WeFlow#28]
不算issue，尝试使用源码打包出来的包，运行在其他平台之后，gulp-sass依赖node-sass，node-sass依赖环境（系统，node版本等），提示需要rebuild node-sass，该问题有什么解决方法呢？

**Comment by littledu** [comment]
你这个问题问得好，或许你还不知道我们在解决这个问题上的辛酸

**Comment by littledu** [comment]
对于 原生模块(c++) ，需要用 Electron 提供的头文件重新编译，如何编译看这里： http://electron.atom.io/docs/tutorial/using-native-node-modules/

然而， node-sass 并没法按这种正规的方式来重新编译，过程就不说了，多少辛酸多少泪，直接给你结果吧：

https://github.com/sass/node-sass/issues/1047#issuecomment-201854319

**Comment by lilijialiang** [comment]
赞！测试了一下，重新编译依赖的win环境较为复杂，mac下重新编译的话木有问题。

**Comment by littledu** [comment]
mac 只占用整个开发时间的百分之三十，大部分时间都在跟 windows 做斗争

**Comment by lilijialiang** [comment]
请问一下，对于node-sass的window重新编译问题，根据 [sass/node-sass#1047 (comment)](https://github.com/sass/node-sass/issues/1047#issuecomment-201854319) 在win7系统下重新编译成功后，切换不同的node版本进行测试还是会提示环境错误

**Comment by littledu** [comment]
编译都是跟具体的 node 版本有关的，

**Comment by Shaman05** [comment]
@littledu 我现在也是碰到这个问题，在win10下开发electron应用碰到require("node-sass")报错了，需要重新编译electron版本的node-sass，捣鼓了好久，但是环境依赖各种蛋疼都快崩溃了。想问下，可否把你编译好的node-sass模块打包发给我，我能直接用吗？

**Comment by littledu** [comment]
@Shaman05 

32位 : http://o92gtaqgp.bkt.clouddn.com/win32-ia32-47/binding.node
64 位：http://o92gtaqgp.bkt.clouddn.com/win32-x64-47/binding.node

替换掉 `node-sass` 下面的 `vendor` 对应的 binding.node 文件。

这里有我搞的一个项目，专门为 electron 编译，可以看看： 
https://github.com/littledu/node-sass-prebuild-for-electron

**Comment by littledu** [comment]
我这个是 node 5.10.0 版本，对应 electron 的版本是 0.37.8，暂时还没时间去升级，如果你不是这些版本，就 fork 一下 https://github.com/littledu/node-sass-prebuild-for-electron ，改一下里面的 appveyor.yml 文件的 node 配置，或者你是哪个版本我来改一下帮你编译一份。

**Comment by Shaman05** [comment]
@littledu 
上面两个都试了，替换掉还是报错了：
ELECTRON_ASAR.js:158 Uncaught Error: %1 is not a valid Win32 application.
\\?\E:\work\electronPrj\nss2\node_modules\node-sass\vendor\win32-x64-48\binding.node

我克隆clone了node-sass-prebuild-for-electron 到本地修改了配置，编译出错了。我的node是6.3.0，electron是1.2.5的，方便的话，帮我编译一份吧，3Q

**Comment by littledu** [comment]
@Shaman05 
试试这个：http://o92gtaqgp.bkt.clouddn.com/win32-x64-48/binding.node

**Comment by Shaman05** [comment]
谢谢！ 替换后报了下面的错误了
ELECTRON_ASAR.js:158 Uncaught Error: Module version mismatch. Expected 48, got 47.

> The major version of node used to build the addon is a different major version of node you're using the addon with.
网上查了下，我的理解是指编译node-sass环境的node版本和使用node-sass的electron用的node环境不一致吧，不知是否正确。

如果是这样的话，我用代码

> var message = [
>             `Node 版本: ${process.versions.node}`,
>             `Chrome 版本: ${process.versions.chrome}`,
>             `Electron 版本: ${process.versions.electron}`,
>             `System: ${config.osType} / ${config.osPlatform}`,
>             `${config.title} 版本: ${config.version}`,
>             `Author: ${config.author} <${config.github}>`
>         ];

得到的node版本是6.1.0，上面的6.3.0是我本机的node环境，能帮我用6.1.0再编译一份吗？谢谢

**Comment by littledu** [comment]
@Shaman05 

http://o92gtaqgp.bkt.clouddn.com/win32-x64-48/binding.node?v=1234

electron: 1.2.5
node: 6.1.0

**Comment by yanhaijing** [comment]
node-sass:-(
