### ISSUE TITLE
是否可以添加编译或者上传时的错误信息，目前上传的时候一直显示执行中，看不出哪里出错

### ISSUE THREAD

**Issue by jokxia** [weixin/WeFlow#29]
#### 运行环境

-操作系统 & 版本：`macOS (10.x.x)`
-  WeFlow 版本： `v1.3.1`

反馈具体描述：
操作执行时，reversion success之后一直处理执行中，看不出错误信息

**Comment by hzlzh** [comment]
上传流程包括 `编译` + `上传`，如果`编译`可以得到正确的 `/dist/` 那就FTP 出了问题，可以用 filezilla 这样的客户端尝试链接一下。

如果编译本身也有问题，可以尝试在项目设置里关闭几个功能试试，`reversion ` 后面还有 `supportWebp` 和 `findChanged `

**Comment by jokxia** [comment]
编译通过的，平时都是filezilla在用，确定地址账号密码都对的

**Comment by hzlzh** [comment]
试一下命令行版本：https://github.com/weixin/tmt-workflow 看看结果如何
在这里配置：https://github.com/weixin/tmt-workflow/blob/master/.tmtworkflowrc#L1

**Comment by mxl0721** [comment]
我这也是一直显示reversion success 
Ftp.raw[mkd](args): Use Ftp.raw('mkd args') instead.
Ftp.raw[feat](args): Use Ftp.raw('feat args') instead
 Ftp.raw[feat](args): Use Ftp.raw('feat args') instead
Message:
    550 The parameter is incorrect

调用窗口有这报错

**Comment by hzlzh** [comment]
试试默认项目，执行是否也是如此？

**Comment by mxl0721** [comment]
我一直在用实例项目，这个报错是什么意思？还有是否与Electron或者其他环境有关？
