### ISSUE TITLE
工作区路径文件夹消失

### ISSUE THREAD

**Issue by Yongd** [weixin/WeFlow#3]
设置好工作区路径后，在finder找不到该文件夹了，里面有重要的数据，回收站里面没有。

**Comment by littledu** [comment]
我重新测试了一下，没有问题啊，默认工作区是在用户名下的根目录，只有新建的项目会在里面

**Comment by Yongd** [comment]
嗯，默认用户名文件夹没错，我是改到了 用户名/sdk/jd_sdk  这个文件夹， 然后返回创建项目，项目名称我没有输入完，我想先确认一下路径，结果找不到  jd_sdkk 这个文件夹了。

**Comment by Yongd** [comment]
设置前
![qq20160618-1](https://cloud.githubusercontent.com/assets/6296303/16169307/7855c3aa-355b-11e6-9932-b91d3ab49f20.png)

设置后
![qq20160618-2](https://cloud.githubusercontent.com/assets/6296303/16169308/7922b20c-355b-11e6-8a0e-b5baccea4bcc.png)

**Comment by littledu** [comment]
你的意思是在修改工作区路径时，已经改了路径，但还没最终确定，切换了一下窗口，回来工作区就不见了是吧。

这里是这样子的，在工作区修改时，失去焦点的时候，我认为你已经确定了，会去更新路径，所以，你看一下你还未完成的路径名是什么，已经改到那里去了。

**Comment by Yongd** [comment]
工作路径是确认好的， 用户名/sdk/jd_sdk  ， 是在创建项目名的时候，没输入完切换了窗口。  
应该不是更换到其他路径了，我全盘搜索了 jd_sdk 目录下的文件，然后没有找到。

**Comment by Yongd** [comment]
工作路径修改到其他路径，然后再改回 用户名/sdk/jd_sdk  这个路径后，看到文件夹了，然后文件夹里面原来的文件都没有了，全部都是创建的项目名文件夹
![qq20160618-3](https://cloud.githubusercontent.com/assets/6296303/16169358/02536160-355d-11e6-9742-f84cea440ed3.png)
![qq20160618-4](https://cloud.githubusercontent.com/assets/6296303/16169359/04f1a97c-355d-11e6-919b-db6dd81d4c8a.png)

**Comment by littledu** [comment]
1. 你更改了工作区路径到 jd_sdk，是正常的
2. 你新建一个项目，项目名没输完，切换窗口
3. 然后发现目录都没了

是这样吗？这不大可能啊，新建项目的时候没有任何删除项目的操作，我按这个流程跑一遍没有问题

**Comment by littledu** [comment]
哦，是这样，这里更新工作区路径，是新建更新，所以不能往原来有内容的目录去更改。

**Comment by Yongd** [comment]
哦，那原来的内容就没有办法找回了么？

**Comment by littledu** [comment]
如果你用 webstorm 这类有历史记录的工具的话，可以把那个目录重建，然后通过 IDE 找回。如果没有，只能用数据恢复软件恢复一下吧，node 删除不会进回收站，原来我们的操作都没有这个流程，是个问题，得改下策略，真是抱歉。

**Comment by littledu** [comment]
不对，更换工作区路径，会复制所有源目录下的项目到目标目录，但不会清空目标目录

**Comment by littledu** [comment]
你的操作是：
1. 更改默认工作区到其他位置
2. 再更改到 jd_sdk 这个目录
3. 然后发现 jd_sdk 这个目录原来的内容没了？

是这样吗？

**Comment by Yongd** [comment]
嗯，是的。昨天忙着重写被删除的数据，所以没来得及看。 数据已经重写的差不多了。

**Comment by littledu** [comment]
这。。。

我按上面的步骤，没法重现啊，你拿两个不重要的目录试试？如果问题存在，这是个非常严重的问题。

**Comment by Yongd** [comment]
这个当时我就重试过，因为我想测试是否是我操作的问题，但是第二次测试时，又没有丢失文件的问题。

**Comment by littledu** [comment]
所以是个意外？

不管怎样，我把这部分逻辑改为挪到回收站，避免这个问题。晚点更新一版

**Comment by Yongd** [comment]
无法判定是不是意外。
改为挪到回收站的办法，可以。
