### ISSUE TITLE
开发环境不能设置autoprefixer吗？

### ISSUE THREAD

**Issue by ouzhou** [weixin/WeFlow#30]
#### 运行环境

- [x] 操作系统 & 版本：`Windows (10)`
- [x] WeFlow 版本： `v1.3.1`

#### 反馈具体描述：
如题，希望提供一个输入需要兼容的level 的输入框或者select（开发版本或者生产版本）

**Comment by hzlzh** [comment]
建议使用 tmt-workflow 可以更灵活的定制 `autoprefixer` 参数，如果需要 `dev` 阶段也有 `autoprefixer`，可以参看这里修改。
https://github.com/weixin/tmt-workflow/blob/master/_tasks/TaskBuildDist.js#L65

**Comment by littledu** [comment]
经过我们自己的实践，认为 开发过程 并不需要给各个浏览器补全。

1. 目前 chrome 等现代浏览器都是支持标准不带前缀的，加前缀为了更加完美的支持旧版浏览器，所以在最后 编译阶段 补全就好了;
2. 开发过程宗旨是响应快，所以一般能不加的功能都尽量不加，即使补全插件的性能很高。
