### ISSUE TITLE
不停的提示请输入项目名称

### ISSUE THREAD

**Issue by xidianwlc** [weixin/WeFlow#31]
#### 运行环境

- [x] 操作系统 & 版本：``Windows 7` 
- [x] WeFlow 版本： `v1.3.1`

#### 反馈具体描述：
安装完成后，进行测试的时候没有输入项目名称，然后weflow就不停的提示请输入项目名称，也不能退出，只能强制杀死进程

**Comment by weidongc** [comment]
我也遇到了。。没输入项目名称点了下后面的按钮。就一直无限弹出提示。关都关不掉。

**Comment by littledu** [comment]
嗯？还有这个问题，我们再排查排查，现在请先输入一下项目名哈。
