### ISSUE TITLE
刚下载的最新的1.3.1，完全处于一种不能用的状态

### ISSUE THREAD

**Issue by Anmout** [weixin/WeFlow#33]
#### 运行环境

- [x] 操作系统 & 版本：`macOS (10.11.4)`
- [x] WeFlow 版本： `v1.3.1`

#### 反馈具体描述：
完全处于一种不能用的状态，点击导入没有反应，点击添加会出现一个空白项目，输入名称后，回车键无法确认，下边四个按钮，点击也完全没有反应

**Comment by hzlzh** [comment]
没有收到过类似反馈，表现比较奇怪。
点击 `cmd+,` 进入全局设置，看一下项目路径是怎样的？会不会是因为没有写入权限造成的。
尝试「导入示例项目」这个按钮能否成功？

你这台设备最近有无进行过重装、变更用户名、升级系统或者 TimeMachine 还原之类的操作，如果有，可能是当前用户的读写权限不足，尝试使用使用系统自带的 `磁盘工具` 诊断一下用户系统权限是否正确，如下图：
![image](https://cloud.githubusercontent.com/assets/1049575/16580862/1e8a5300-42d9-11e6-853b-3fc2cdfec8e4.png)

**Comment by Anmout** [comment]
不好意思，确实是我电脑权限问题，感谢您的解决方案
