### ISSUE TITLE
停在 `copyMedia` 过不去了

### ISSUE THREAD

**Issue by sinceow** [weixin/WeFlow#34]
+ Mac 10.11.5
+ WeFlow 1.3.1

停在 `copyMedia`了，`media`目录中放了一个 fonts 文件夹和两张图片，之前一直可以，今晚就编译过不了了

```
[22:49:10] compileLess success.
[22:49:10] compileSass success.
[22:49:10] compileAutoprefixer success.
[22:49:13] miniCSS success.
[22:49:13] imageminImg success.
[22:49:13] imageminSprite success.
[22:49:17] uglifyJs success.
[22:49:17] copyMedia success.
```

**Comment by sinceow** [comment]
开发是完全正常的

**Comment by hzlzh** [comment]
按你所说，我本地没有重现。
所以尝试一下从新导出一个全新 demo，然后把 media 文件内容挪动进去看有什么结果

**Comment by sinceow** [comment]
经过我的测试

**Comment by sinceow** [comment]
经过我的测试
只要有BuildJS，那就不能正常的生产编译了，JS的压缩任务可能有点问题，我想安装tmt-workflow 来看下LOG，结果 tmt-workflow 又一直卡在 `cwebp-bin` 的安装。。。

```
<!-- build:js -->
```

**Comment by hzlzh** [comment]
跟你你的反馈，问题应该出在 js 文件里，你尝试用 jslint 过一遍，看看是不是有什么格式或者语法错误。

另外，关于 `tmt-workflow` 的依赖你可以用 `cnpm` 试试。

**Comment by sinceow** [comment]
我用 tmt-workflow 看到 LOG了

是 `usemin` 插件出的错 `no writecb in Transform class`，GOOGLE了一圈这个问题很普遍，但没什么确切的解决方案，貌似跟 Node 有关，暂时处理不了，切换回Gulp先用着，希望你们能发现问题

```
➜  project git:(master) ✗ node -v
v4.2.6
➜  project git:(master) ✗ npm -v
2.14.12
```

**Comment by hzlzh** [comment]
好的多谢，能否附一个会引起报错的代码段或者文件，方面我们重现定位。

**Comment by sinceow** [comment]
不是由某一个文件引起的，只要添加了JS需要进行压缩就会中断， 就像下在这样只加个Underscore就出错了，只要不加入JS就能正常，应该是 `usemin` 和 `Node.js` 引起的问题
```
   <!-- build:js ../js/build.js -->
    <script type="text/javascript " src="../js/underscore.js "></script>
    <!-- endbuild -->
```

**Comment by hzlzh** [comment]
好的，已经重现

**Comment by sinceow** [comment]
希望你们能早点解决，release 一个新版本。

还有一个问题就是使用 (framework7 )[http://framework7.io/] 时，样式表中的 `.row` , `.col-*`在压缩的过程中会产生数据偏差。可能所有的通过 `calc` 计算的样式都会发生偏差。

**Comment by sinceow** [comment]
希望你们能早点解决，release 一个新版本。

还有一个问题就是使用 [framework7](http://framework7.io/) 时，样式表中的 .row , .col-*在压缩的过程中会产生数据偏差。可能所有的通过 calc 计算的样式都会发生偏差。

**Comment by hzlzh** [comment]
这两个问题已录入计划，后续会优化。
