### ISSUE TITLE
WeFlow-win32-x64 在win10上运行不了

### ISSUE THREAD

**Issue by taoqier** [weixin/WeFlow#35]
![image](https://cloud.githubusercontent.com/assets/11536612/16680365/82e05c84-4520-11e6-82fd-12ccde91d67c.png)

**Comment by littledu** [comment]
你的 win10 是几位的？

**Comment by zuibunan** [comment]
几个月前试了下，右上角菜单新建项目，然后就一直弹窗名字不对
![image](https://cloud.githubusercontent.com/assets/3386786/17245523/6dab2944-55b9-11e6-827c-356ebea5983e.png)

前几天又试了下，问题依旧

win10，64bit

**Comment by littledu** [comment]
@taoqier 的是 32 位，在 1.3.2 之前都是不支持的，现在试一下 1.3.2 版本

**Comment by littledu** [comment]
@zuibunan 我们在前天发布了 1.3.2 版，已经修复不输入项目名时的弹窗终止不了的问题
https://github.com/weixin/WeFlow/releases/tag/1.3.2
