### ISSUE TITLE
希望添加一些API

### ISSUE THREAD

**Issue by andypinet** [weixin/WeFlow#38]
#### 关于 Issues 的提交说明
`feature`

#### 反馈具体描述：

你们基于gulp4的这个流处理工具很好 但是灵活性不足 
我建议 在less 或 sass中开始提供一些更高级的API 

less 或者 sass 其实就是前端一个很好的处理语言 为什么放弃这么好的语言 非要自己包装一些功能
比如image 的size 不仅仅是添加就完事 其实其他ui也可能需要这些参数

* file API 
   * file-exist 
* image API
   * image-size      less有相关的功能  sass需要自己扩充
* color API
   * 。。。  更多的颜色函数
* math API
  * 。。。   更多的数学函数  这个在做动画时很实用 比如 sin cos tan

**Comment by littledu** [comment]
嗯？我们同时间支持 `LESS` 和 `SASS`啊，所以完全可以自由选择。

实际上我们提供了两套，一套命令行式轻量级的 [tmt-workflow](https://github.com/weixin/tmt-workflow), 方便自由修改。一套封装好的 `WeFlow`，不需要安装。下载即能用。
