### ISSUE TITLE
app打开crash、报错

### ISSUE THREAD

**Issue by seasonscao** [weixin/WeFlow#39]
#### 运行环境

- [x] 操作系统 & 版本：macOS (10.11.15)
- [x] WeFlow 版本： v1.3.1

#### 反馈具体描述：
项目文件夹拖进app一直没有反应，com+Q以后报错：

Uncaught Exception:
Error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: undefined.
    at callIntoRenderer (/Applications/WeFlow.app/Contents/Resources/electron.asar/browser/rpc-server.js:193:19)
    at MenuItem.click (/Applications/WeFlow.app/Contents/Resources/electron.asar/browser/api/menu-item.js:81:16)
    at Function.delegate.executeCommand (/Applications/WeFlow.app/Contents/Resources/electron.asar/browser/api/menu.js:119:40)

**Comment by littledu** [comment]
这倒是第一次在 mac 下收到这样的问题，10.11.15 这个版本回头我升级试下。

**Comment by seasonscao** [comment]
@littledu 好的，希望尽快修复.. 现在深度使用 weflow

**Comment by hzlzh** [comment]
@seasonscao 你反应的这个报错后 WeFlow 无法退出，可以强制结束任务（command+option+ESC 键）。
建议目前先用底部工具栏的（+号）或者 Command+O 来载入项目，不要直接拖拽可以正常使用。
这个反馈已经记录，等后续优化修复吧。

**Comment by seasonscao** [comment]
@hzlzh 根据你的方法尝试了一下，但是一直运行项目文件夹，点击打开后无法正常打开，新建项目，点击开发，底部显示running 但也无反应。

**Comment by hzlzh** [comment]
导入默认项目呢？能正常运行否？

**Comment by seasonscao** [comment]
@hzlzh 试着把weflow带着默认项目的文件夹删了重新安装，现在example运行没问题了，但是我的项目，一直在running，是因为我在结构src中增加了libs和scss文件夹的关系吗？

**Comment by hzlzh** [comment]
是的，WeFlow 有默认的项目结构，task 在处理的时候也是依赖这样的逻辑的，参看一下这里：
https://github.com/weixin/tmt-workflow#项目目录结构

对你的项目目录进行调整就可以正常运行了。

另外，你反映的拖入文件夹报错我们已经重现了，这个后续会修复。

**Comment by seasonscao** [comment]
多谢~ 祝愿你们越来越好~
