### ISSUE TITLE
无限弹窗

### ISSUE THREAD

**Issue by s749312025** [weixin/WeFlow#40]
#### 运行环境

- [x] 操作系统 & 版本：`Windows 8.1` 
- [x] WeFlow 版本： `v1.3.1`

#### 反馈具体描述：
新建项目的时候，还未输入项目名，点击后面的项目设置，无出现请输入项目名的无限弹窗；
点击前面的在文件中查看也是一样；
出现已有项目名，也是无限出现这个弹窗

**Comment by littledu** [comment]
get
