### ISSUE TITLE
Autoprefixer 能配置参数吗？

### ISSUE THREAD

**Issue by sjmlsxp** [weixin/WeFlow#41]
#### 运行环境

- [x] 操作系统 & 版本：`macOS (10.11.6)`
- [x] WeFlow 版本： `v1.3.1`

#### 反馈具体描述：
比如display: flex;属性，build后display: -ms-flexbox;display: flex;
只有添加了-ms私有属性，对于实际项目而且太“先进”了
能开放个参数，来配置autoprefixer吗？

**Comment by hzlzh** [comment]
目前暂不支持定制 `Autoprefixer` 的参数，如果确实有需求建议尝试使用 [tmt-workflow](https://github.com/weixin/tmt-workflow/) 来定制，参见：
https://github.com/weixin/tmt-workflow/blob/master/_tasks/TaskBuildDist.js#L65

另外，你的这个反馈意已经收录到 WeFlow 的讨论 issue 里，未来如果支持将会告知你。

**Comment by sjmlsxp** [comment]
weflow能改下默认的Autoprefixer参数，再更新一个版本吗？
现在的情况，对于真实项目而言太过“先进”，没法用于生产环境

 tmt-workflow 装起来太辛苦了/(ㄒoㄒ)/~~

**Comment by hzlzh** [comment]
<img width="336" alt="screen shot 2016-07-25 at 5 35 04 pm" src="https://cloud.githubusercontent.com/assets/1049575/17096962/50cb5764-528e-11e6-9cf5-f17d8f551b75.png">
目前你可以考虑打开 App 修改本地的版本，关于配置的事宜我们讨论一下纳入未来版本的规划。

**Comment by littledu** [comment]
WeFlow 目前用的参数为 `last 5 versions`, 也就是各个浏览器最新的 5 个版本，对于绝大多数浏览器来讲，最新的 5 个版本均以支持 `flex` 的标准版本，而 IE 则还不支持，所以，自动补全的就是 `display: -ms-flexbox;display: flex;`，这是正确的。

楼主在项目中对于这两个补全尚觉得不足是吗？

**Comment by littledu** [comment]
经讨论，下一版支持，这一两天更新。
