### ISSUE TITLE
1.3.1 MAC版一堆BUG，根本不能用

### ISSUE THREAD

**Issue by evenle** [weixin/WeFlow#44]
#### 运行环境

- [x] 操作系统 & 版本：`macOS (10.9.5)`
- [x] WeFlow 版本： `v1.3.1`

#### 反馈具体描述：
1.3 MAC版一堆BUG，根本不能用
工作路径也不对，改了也没有用，新建项目也不行，也打不开，根本就是用不了!

**Comment by hzlzh** [comment]
能否具体描述一下你所说的 bug，目前没有收到类似完全不能用的反馈，不过 macOS 10.9.5 我们要具体测试一下。
另外，把所有项目列表删除，导出范例项目试试如何？

**Comment by hzlzh** [comment]
1.3.2 已发布，试试最新的吧
https://weflow.io/#download
