### ISSUE TITLE
一个建议：可不可以自己定义选择输出目录呢

### ISSUE THREAD

**Issue by waynecz** [weixin/WeFlow#46]
#### 运行环境

- [x] 操作系统 & 版本：`macOS (10.11.2)`
- [x] WeFlow 版本： `v1.3.1`

#### 反馈具体描述：

因为WeFlow的功能确实强大，但是偶尔会有需要嵌入到别的的开发框架里的情况，如果能指定开发和编译的目录的话会方便很多。

**Comment by sinceow** [comment]
我也想有这么个功能，就是输出目录和输入目录可以手动选择，但目录可以还是原来的那些

**Comment by littledu** [comment]
WeFlow 是基于 tmt-workflow 的一个 GUI 工具，如果这么改的话，改动有点大，所以，这种较大变动的定制，我更希望大家可以直接去 fork 一份 tmt-workflow 修改定制，这样会更方便。有什么相关的问题可以交流。

**Comment by hzlzh** [comment]
给你们提供一个思路，使用 linux 的 ln 命令创造软链。
比如你要在 `/users/xxx/project-xxx` 里使用 WeFlow 某个项目里的 ./dist/ 产出文件，那么做一个软链就好了，这样可以保持同步更新。

```bash
ln -s dist /Users/hzlzh/Projects/wechat-game/dist/
```
