### ISSUE TITLE
【功能建议】软件添加一个窗口缩小到托盘

### ISSUE THREAD

**Issue by chasonma** [weixin/WeFlow#47]
如题！

**Comment by hzlzh** [comment]
多谢你的建议，我们刚才讨论了一下：

通常 Window 右下角托盘区以及 macOS 的右上角 Menu 区承载着一些有常驻需求的软件功能，比如开机自启动的 杀毒软件或者输入法等软件。

不过考虑到一些软件也提供了这样的功能，来保持 Mac Dock 或 Window 底部更精简整洁，我们觉得还是有必要在未来的版本支持这个功能，初步计划是一个选项「用来控制关闭按钮的收起逻辑」，后面有更新也会第一之间告诉你哟~
