### ISSUE TITLE
关于项目目录

### ISSUE THREAD

**Issue by xcsweb** [weixin/WeFlow#53]
#### 关于 Issues 的提交说明
请附注以下信息，这将有助于你的 Issues 被更好、更及时的回复和处理：  
建议补充 `报错代码` 或者 `问题截图`，同时，请确保你运行的是 **最新发布的版本**，因为问题可能已经修复。

__ 以上文本阅读后请删除 __

#### 运行环境

- [x] 操作系统 & 版本：`macOS (10.x.x)` / `Windows (7/8/10)` / `Linux`  
- [x] WeFlow 版本： `v1.x.x`

**Comment by xcsweb** [comment]
对于输入，输出，测试这三个目录没有问题，能不能做个映射，比如输入的less对应输出的css，这样，有点类似于koala    http://koala-app.com/index-zh.html，目录之间比较自由，文件一一对应这样

**Comment by littledu** [comment]
不是很明白

**Comment by xcsweb** [comment]
就是说比如有个css的目录，我不想要把css文件输出到css目录，但默认是输出到css目录，现在我想修改输出到style目录下，就是这个意思

**Comment by hzlzh** [comment]
WeFlow 是不支持这样的定制的，建议看一下 https://github.com/weixin/tmt-workflow
可以根据自己的想法对目录结构进行改动。
