### ISSUE TITLE
建议添加自定义索引目录功能

### ISSUE THREAD

**Issue by 68zch** [weixin/WeFlow#54]
我的项目目录跟软件自动生成的不一样，比如我在src下面新建一个文件夹aaa，编译或者发布后并没有这个文件夹aaa

**Comment by littledu** [comment]
参照 tmt-workflow 的 wiki: https://github.com/weixin/tmt-workflow/wiki/%E2%92%89-%E7%9B%AE%E5%BD%95%E7%BB%93%E6%9E%84

**Comment by 68zch** [comment]
不是太明白，配置文件里只有是否支持rem,webP等的开关，并没有自定义个性化文件目录的功能啊，希望能回答的详细些，最好给个例子。
另外再描述下我的问题：
现在自动生成的目录是这样的：
src
--css
--html
--img
--js
--media
--slice
我想变成这样的目录该怎么修改
src
--css
--script
--views
--images
--uploads
--icon
--module
--template

**Comment by littledu** [comment]
目前不支持自定义个性化目录

一个流程，是建立在一定的规范下的，如果你要自定义个性化目录的话，建议 修改 [tmt-workflow](https://github.com/weixin/tmt-workflow) 达到你想要的目的（修改过程有什么问题可以交流）。

**Comment by 68zch** [comment]
一个流程，是建立在一定的规范下的。这一点我同意，目前的目录不太适合我现在的项目，感觉自动生成的目录更加适合写简单的静态页，看来只能自己配置gulp了。希望这个软件能推出这个功能，这样会更加灵活。
