### ISSUE TITLE
/fonts该如何引用

### ISSUE THREAD

**Issue by Foundj** [weixin/WeFlow#55]
#### 关于 Issues 的提交说明
bootstrap 等都引用fonts字体包，
在使用 weflow 中，这些字体包该如何处理？

**Comment by littledu** [comment]
放在 media 目录里面

**Comment by Foundj** [comment]
感谢！是否可以考虑把 js,fonts,img等放到assets文件夹里更好？或者说给一个配置？

**Comment by littledu** [comment]
这个是我们团队的结构标准，配置的话在 weflow 不方便改，你可以 fork [tmt-workflow](https://github.com/weixin/tmt-workflow) 修改成你们团队的结构配置。
