### ISSUE TITLE
编译后的文件的浏览器兼容性做到了何种程度？

### ISSUE THREAD

**Issue by shenxiang11** [weixin/WeFlow#56]
现在发现display:flex,在ios7中不能够用。

**Comment by littledu** [comment]
用的 autoprefixer，已经是加到 9 了，满足所有机型，如果你没有正确生成 `-webkit-box` 等，看看是不是 WeFlow 没升级

`postcssAutoprefixer({browsers: ['last 9 versions']})`

**Comment by evolutionjay** [comment]
从神飞的博客过来看的，本来想用的，居然不给配置。 弃。
