### ISSUE TITLE
Uncaught Error: Missing binding /Users/king/work/github_rep/WeFlow/node_modules/node-sass/vendor/darwin-x64-47/binding.node Node Sass could not find a binding for your current environment: OS X 64-bit with Node.js 5.x

### ISSUE THREAD

**Issue by love-yoyo** [weixin/WeFlow#58]
#### 运行环境

- [x] 操作系统 & 版本：`macOS (10.11.5)`  
- [x] WeFlow 版本： `v1.3.2`
- [x] Node： `v4.2.2`
- [x] npm： `v3.3.6`

#### 反馈具体描述：
`npm start`之后打开界面，但dev tool上显示
```
Uncaught Error: Missing binding /Users/king/work/github_rep/WeFlow/node_modules/node-sass/vendor/darwin-x64-47/binding.node
Node Sass could not find a binding for your current environment: OS X 64-bit with Node.js 5.x

Found bindings for the following environments:
  - OS X 64-bit with Node.js 4.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to build the binding for your current environment.
```
![image](https://cloud.githubusercontent.com/assets/8407958/17721989/1636930e-6461-11e6-866d-90fc2f256be3.png)

#### 疑问
1. node版本是否需要5以上？但是官网稳定版是4.x，是否可以考虑兼容一下？

**Comment by littledu** [comment]
目前我们使用的 Electron 版本是 0.37.8，此版本的 node 版本是 5.10.0，如果你一定要在 4.x 版本下运行，得找到 Electron 相应的版本，建议在开发时，外部环境的 node 版本与 Electron 的 node 版本一致，避免因版本导致的问题。

建议往前升而不是往后降，因为现在 Electron 已经到 1.3.3 版本了，我们已经准备跟进升级了。

**Comment by love-yoyo** [comment]
了解，谢谢
