### ISSUE TITLE
自带的命令行小窗口报错太不明显了，请求下一版本添加报错时桌面弹窗吧

### ISSUE THREAD

**Issue by zhengshuai1001** [weixin/WeFlow#59]
- [x] 操作系统 & 版本：Windows (10)
- [x] WeFlow 版本： `v1.3.2`

有时候scss变量写错了，编译就会失败，页面就没有效果。如果WeFlow报错时能桌面弹窗提醒，就太好了。

![sp160820_173315](https://cloud.githubusercontent.com/assets/9513530/17830391/8c59d918-66fc-11e6-9d1d-4a736a55810c.png)

**Comment by littledu** [comment]
没有效果不就是最好的提醒了么

**Comment by zhengshuai1001** [comment]
额，好有道理的样子，，，可是每次发现没效果，第一反应是css写的不对，不会考虑写错了啊，，看样子编辑器还得加个scss检测的插件。。。

**Comment by littledu** [comment]
嗯，这个需求还是值得讨论的，我们后面看看，可以考虑加一下这个功能，

**Comment by zhengshuai1001** [comment]
非常谢谢
