### ISSUE TITLE
卡在某个界面不动了。

### ISSUE THREAD

**Issue by xiamu14** [weixin/WeFlow#6]
![image](https://cloud.githubusercontent.com/assets/10813360/16185055/af36766e-36f3-11e6-9da6-96d918ecb1a6.png)

点击确定，或关闭按钮还是弹出这个小窗口。

**Comment by littledu** [comment]
是最新版吗

**Comment by xiamu14** [comment]
是的。才刚下载下来的。win10系统。

**Comment by xiamu14** [comment]
![image](https://cloud.githubusercontent.com/assets/10813360/16185135/43391ede-36f4-11e6-98e9-f4ae6d5f9572.png)
我是没有在项目那里输入项目名称，然后点击开发就弹出 提示“输入项目名称”的小窗口。但是小窗口关不掉，应用也关不掉

**Comment by littledu** [comment]
嗯，好的，正在安装 win10 虚拟机

**Comment by hzlzh** [comment]
已经重现了，加入下一版修复计划中，目前先使用资源管理器结束掉进程重新打开就可以了。
