### ISSUE TITLE
WeFlow好像只能默认生成 style-index.less 文件，能否全局设置成默认使用sass啊

### ISSUE THREAD

**Issue by zhengshuai1001** [weixin/WeFlow#60]
自动生成的都是less文件，我们开发用的是scss，感觉不方便啊！！！

- [x] 操作系统 & 版本：Windows (10)
- [x] WeFlow 版本： `v1.3.2`

**Comment by littledu** [comment]
你用 .scss 就自动变成 sass 你试试

**Comment by zhengshuai1001** [comment]
嗯，我知道，我的意思是他自动生成的less文件岂不浪费了么~~~我还要在html页添加css link ,要是它能默认sass就好啦 :grin:

**Comment by littledu** [comment]
你可以进源文件把我的模板改成你自己要的，后面我们考虑给个接口方便替换

**Comment by zhengshuai1001** [comment]
OK，我去看看:grin:
