### ISSUE TITLE
新建项目模板失效

### ISSUE THREAD

**Issue by zhengshuai1001** [weixin/WeFlow#61]
- [x] 操作系统 & 版本：Windows (10)
- [x] WeFlow 版本： `v1.3.2`

软件自动生成的项目文件结构和自己的需求有点不符，我稍微更改了下这个文件夹里的东西：WeFlow-win32-x64\resources\app\templates的project文件夹，就不好使了，只是稍微修改html文件夹下index.html的某一行，然后运行软件时，新建项目，在项目目录下会出现project，之前都是直接出现src文件夹，然后点击开发，dev文件夹也没生成，编译，打包等都没生成

**Comment by hzlzh** [comment]
试试吧 project.zip 解压出来会发现 src/ 目录，修改成你自己想要的结构和文件之后重新打包成 project.zip 覆盖回去
