### ISSUE TITLE
打包成window 应用没反应

### ISSUE THREAD

**Issue by lebornjose** [weixin/WeFlow#62]
#### 关于 Issues 的提交说明
请附注以下信息，这将有助于你的 Issues 被更好、更及时的回复和处理：  
建议补充 `报错代码` 或者 `问题截图`，同时，请确保你运行的是 **最新发布的版本**，因为问题可能已经修复。

__ 以上文本阅读后请删除 __

#### 运行环境

- [x] 操作系统 & 版本：`macOS (10.x.x)` 
- [x] WeFlow 版本： `v1.3.2`

**Comment by littledu** [comment]
你是在哪个系统下打包，你参考 appvear.yml 文件，里面有我在 Windows 下的打包流程，不是那么简单的

**Comment by lebornjose** [comment]
在mac 下打window包。 能给我简单說下在mac 下打window 包的流程吗

**Comment by littledu** [comment]
你去看一下那个 electron-packager，其实是一样的，只是有些编译的模块是无法这样跨平台编译的，如果只是非常简单的代码，则可以。这也是我们为什么搞自动化编译的原因。
