### ISSUE TITLE
我修改了样式，为什么浏览器不自动刷新呢，手动也不行

### ISSUE THREAD

**Issue by xcsweb** [weixin/WeFlow#64]
#### 关于 Issues 的提交说明
请附注以下信息，这将有助于你的 Issues 被更好、更及时的回复和处理：  
建议补充 `报错代码` 或者 `问题截图`，同时，请确保你运行的是 **最新发布的版本**，因为问题可能已经修复。

__ 以上文本阅读后请删除 __

#### 运行环境

- [x] 操作系统 & 版本：`macOS (10.x.x)` / `Windows (7/8/10)` / `Linux`  
- [x] WeFlow 版本： `v1.x.x`

**Comment by xcsweb** [comment]
我修改了样式，为什么浏览器不自动刷新呢，手动也不行，是不是还要开什么，我这边已经开启了liveReload

**Comment by littledu** [comment]
要修改 src 下的 .less 文件，不会自动刷新的可能就是代码有错，你打开 log 面板或开启调试模式看看报错信息

**Comment by xcsweb** [comment]
我知道了，我把style-index.css改成all.css就不行了，虽然css文件夹里面的style-index.less也被我改成了all.less也不行，有没有更好的解决方法呢

**Comment by xcsweb** [comment]
我测试了一下，必须要加style-*前缀

**Comment by littledu** [comment]
你可以查看 example，这是我们的规范要求，了解一下就知道了
