### ISSUE TITLE
sass 编译出错能不能提醒下？

### ISSUE THREAD

**Issue by zaxlct** [weixin/WeFlow#65]
可能某一句 sass 写错了，然后就不编译了。也不提醒到底那一句编译错了，要手动找很久，太麻烦了。

**Comment by littledu** [comment]
有两种方式：

1. 点击右下角的 `查看日志`， 打开 log 面板可以看到报错
2. `窗口-调试模式`，打开 开发者工具，也可以查看到日志

**Comment by zaxlct** [comment]
OK，谢谢。问题已解决！
