### ISSUE TITLE
内网测试的时候,我分享出去的ip打开的页面

### ISSUE THREAD

**Issue by xcsweb** [weixin/WeFlow#67]
内网测试的时候,我分享出去的ip打开的页面，人家打开鼠标滑动页面，我的页面也跟着滑动了

**Comment by xcsweb** [comment]
这是怎么回事呢

**Comment by littledu** [comment]
这是开发时候的功能，自动监听源文件变动，自动刷新浏览器，你说的这个是它的另一个，远程同步功能，可以方便用来演示调东西。
