### ISSUE TITLE
iconfont的字体图标文件，怎么处理？

### ISSUE THREAD

**Issue by qq157788394** [weixin/WeFlow#68]
#### 运行环境

- [x] 操作系统 & 版本：`macOS (10.x.x)`
- [x] WeFlow 版本： `v1.3.2`

#### 反馈具体描述：

iconfont的字体图标文件，怎么能让他自己复制过去？

**Comment by littledu** [comment]
media 目录

**Comment by qq157788394** [comment]
谢谢
