### ISSUE TITLE
能自己定义项目的脚手架吗？

### ISSUE THREAD

**Issue by shuchengliang** [weixin/WeFlow#7]

**Comment by littledu** [comment]
WeFlow 依赖于 [tmt-workflow](https://github.com/weixin/tmt-workflow), 有一定的目录结构要求，现在新建项目也都是按照那个结构去创建的，可以做一个功能，让用户自已提供一个压缩包，压缩包里面的结构按 tmt-workflow 的规范来就好，用户能操控的就是里面的文件。

**Comment by shuchengliang** [comment]
@littledu 恩，刚按照tmt-workflow的目录结构新建的一个项目模板放到WeFlow-win32-x64\resources\app\templates里替换project.zip，再点新建项目就是自己想要的初始模板了，如果这里有新建项目选择模版会更好。

**Comment by littledu** [comment]
嗯，点 + 号有个上拉框，内容为 `新建模版一项目`， `新建模版二项目`, 我 mark 一下。
