### ISSUE TITLE
哪种格式的图片压缩之后质量最小最清晰啊

### ISSUE THREAD

**Issue by xcsweb** [weixin/WeFlow#70]
#### 关于 Issues 的提交说明
请附注以下信息，这将有助于你的 Issues 被更好、更及时的回复和处理：  
建议补充 `报错代码` 或者 `问题截图`，同时，请确保你运行的是 **最新发布的版本**，因为问题可能已经修复。

__ 以上文本阅读后请删除 __

#### 运行环境

- [x] 操作系统 & 版本：`macOS (10.x.x)` / `Windows (7/8/10)` / `Linux`  
- [x] WeFlow 版本： `v1.x.x`

**Comment by hzlzh** [comment]
WeFlow 里集成了自动化压缩 [gulp-imagemin](https://github.com/sindresorhus/gulp-imagemin)。
对于 png 格式效果会好一点，因为 jpg 通常已经经过设计师导出时压缩这一步。

如果是手动处理：
通常来讲，要根据图片实用场景来看：

有透明度要求的图：导出 PNG 格式，然后过一次诸如：  tingpng.com 压缩效果比较好
无透明度要求的图：导出 JPG 时选择对应的压缩质量（比如我们常用 30 或 40）即可，（或者可以保存高质量（如：质量 100 或 80） 的 JPG 然后再过一次诸如： tingpng.com 压缩）

比如 Photoshop 的操作：
![image](https://cloud.githubusercontent.com/assets/1049575/18228870/77c8fe6e-7293-11e6-8c52-59306967aef3.png)
