### ISSUE TITLE
问个问题关于ie

### ISSUE THREAD

**Issue by xcsweb** [weixin/WeFlow#71]
当我内网测试的时候，是localhost这个样子。chrome和360浏览器急速都能运行js，ie浏览器不运行，360的兼容模式network的时候js都没有加载，但是我看了dev文件里面是有js的，html也有写，然后找到dist文件直接打开file://这样,ie浏览器弹了一个
https://cloud.githubusercontent.com/assets/20693737/18190151/01ec89f0-70f3-11e6-8ff4-176f836a6db2.png,把这个链接复制到浏览器输入框即可看，大概是allow run script,然后js就可以运行了，
我不知道是什么问题啊，以前也没遇到过

**Comment by xcsweb** [comment]
大概是我的ie问题

**Comment by hzlzh** [comment]
最好有一个本地的服务器来托管页面，比如 webstorm 里直接点击预览 html 会得到这样的地址：
http://localhost:63342/xxx/index.html 就没问题。

也可以启一个 nodejs 或者 php 服务来预览就没问题了。
