### ISSUE TITLE
Sass 怎么适配 REM？怎么自动压缩图片？

### ISSUE THREAD

**Issue by zaxlct** [weixin/WeFlow#72]
### Sass 怎么适配 REM？
把 lib_rem.less 改成 lib_rem.scss 引入到项目里，然后开启了 REM 解决方案，不过调试的时候没发现字体的单位变成 REM 了

**Comment by littledu** [comment]
开发 阶段不做 REM 的转换，你执行一下 编译 ，在输出的 dist 目录里就可以看到
