### ISSUE TITLE
如何我只用vue的话,是可以编译的,但是我又把vue.router下载了下来

### ISSUE THREAD

**Issue by xcsweb** [weixin/WeFlow#73]
var Vue = require('vue');
var VueRouter = require('vue-router');
Vue.use(VueRouter);
有个require,报错是require is not defined，这是http://router.vuejs.org/zh-cn/installation.html，
我想用他,但是不知道该怎么办了

**Comment by littledu** [comment]
请去 vue 的相关 github 上问
