### ISSUE TITLE
在开发者工具中的css样式可否显示成来自scss文件？

### ISSUE THREAD

**Issue by numens** [weixin/WeFlow#74]
使用sass开发的时候，谷歌的开发者工具显示的样式是来自css的，可否改成样式来自scss文件？（已按网上修改了浏览器设置，用koala编译时可以看到样式来自scss）

#### 运行环境

- [x] 操作系统 & 版本： `Windows 7` 
- [x] WeFlow 版本： `v1.x.x`

**Comment by hzlzh** [comment]
scss 在 Devtools 里直接显示需要配合 sourcemap 的使用，参看这里：
https://robots.thoughtbot.com/sass-source-maps-chrome-magic
