### ISSUE TITLE
功能And配置需求

### ISSUE THREAD

**Issue by evolutionjay** [weixin/WeFlow#76]
#### 运行环境

- 操作系统 & 版本：`macOS (10.11.6)` 
- WeFlow 版本： `v1.3.2`

##### 功能需求
- Dev 的 CSS 编译需要 Autoprefix 前缀补全，因为就算是开发，也要测试浏览器兼容。
- Autoprefix 需要配置浏览器版本，请给出配置选项。

**Comment by littledu** [comment]
1. 开发阶段补全功能之前我们有尝试开过，后来发现实在是没太大必要，因为习惯性的我们只会在一个浏览器上进行开发，而不会是每写一点就去所有浏览器上看效果，所以，最后打包编译补全过一遍浏览器兼容即可。

2. 目前 补全 支持到 9 个版本，已经覆盖几乎所有能覆盖的，为什么要配置呢？

**Comment by evolutionjay** [comment]
1. 这个习惯我觉得太主观，请客观看待一个软件的发展要具备的素质。

2. 万一我不需要全部覆盖呢？

**Comment by littledu** [comment]
人有太多太多，需求也都不全是一样，今天你想的是应该这个样子，明天有朋友觉得没必要，那咋办呢？就好比之前我们在开发阶段就自动将 px 转换成 rem，保证开发阶段跟最终编译生成的都是一样的，但有朋友反馈说不方便调试，而且编译后结果其实都是一样的，我们也有同样的感觉，所以后来就去掉了这个功能。

关于 覆盖 这个问题，之前也是有朋友反馈不够全，所以从 5 调成 9。

如果要满足所有人，就必需都做成非常灵活可配置的，这只是其中一个，所有的功能都想做成灵活可配置的，那这个配置就太复杂了点，大部分用户在使用的时候，都不会怎么去认真看文档说明，所以我们更希望的是越简单越好，配置越多，反而复杂化了。

什么都满足不是很现实，如果无法满足需求，也是可以直接在源码的基础上修改成自己想要的样子，

**Comment by evolutionjay** [comment]
好吧， 那么直接 gulp 吧。 close 吧

**Comment by littledu** [comment]
https://github.com/weixin/tmt-workflow

相信这个基于 gulp4 的可以很方便的修改

**Comment by evolutionjay** [comment]
虽然不是来踩场子，但是我发现我提的需求，别人的app已经做了。
作者搜搜 Codekit

**Comment by hzlzh** [comment]
CodeKit 是比较老牌的前端工具了，如果能满足到你的需求建议直接购入使用。
WeFlow 更多的是开源和可定制性，跨平台的特性也能覆盖到 Windows 和 Linux 用户的使用需求，所以二者诞生的出发点不同。
