### ISSUE TITLE
不知道是不是我使用的问题

### ISSUE THREAD

**Issue by cssxn** [weixin/WeFlow#77]
我用flow做了两个页面，设计图是375的尺寸，我是按照标注的px来写的。

开启rem以后，编译完成，dist目录下面的竟然和dev的页面有很大差异。

dev下的全部是px的，没有转rem。

求rem正确使用姿势

**Comment by hzlzh** [comment]
这里的逻辑是 dev 阶段不用关注不同尺寸设备的兼容，因为后面会自动化的使用 rem 方案来完成。所以开发时在你预设的尺寸下调试就好，比如我们是 375px iPhone 6 的宽度下进行 dev

**Comment by cssxn** [comment]
但是通过自动化rem转换以后，dev目录和dist目录下的代码同时在iphone6上展示的却有些不同，我觉得是字体的原因

**Comment by hzlzh** [comment]
dev 是供编码调试阶段在电脑上预览的，如果要在手机上体验直接用 dist 的版本就好。
目前 root font size 基准值默认约定为 20:1 ，如果需要定制建议使用 tmt-workflow 的版本，自行定制下面两处即可。

另外 HTML 里 rem 的触发方式是：`<html lang="zh-CN" data-rem="375">`

https://github.com/weixin/tmt-workflow/blob/master/_tasks/TaskBuildDist.js#L78
https://github.com/weixin/tmt-workflow/blob/master/_tasks/TaskBuildDist.js#L185

**Comment by cssxn** [comment]
@hzlzh  我之前使用的是老版本的weflow，那个版本的dev下的也是转换过rem单位的

**Comment by hzlzh** [comment]
@cssxn 恩，新版去掉了，不过我们现在考虑下一版本加回来，因为不止你一个对此有异议。
对于熟悉流程的开发者，其实 dev 阶段不关心 rem 即可，我们在公司开发的时候就是这样，相当于完全信任 rem 后面的兼容处理。
