### ISSUE TITLE
求个国内下载的地址，github上下载不下来

### ISSUE THREAD

**Issue by CharlesSong** [weixin/WeFlow#8]
求个国内下载的地址，github上下载不下来

**Comment by xiamu14** [comment]
翻墙可以下载。

**Comment by CharlesSong** [comment]
一翻墙，能ping通域名，还是不行

**Comment by xiamu14** [comment]
https://pan.baidu.com/s/1geEM70B    百度云下载地址……

**Comment by littledu** [comment]
已经更新到七牛，到官网下载即可。
官网： https://weflow.io/

![image](https://cloud.githubusercontent.com/assets/1784673/16194516/8196fec0-3727-11e6-91f0-ebce24b1aa6f.png)

**Comment by littlebaozi** [comment]
无法访问，找不到 cdn.weflow.io 的服务器 DNS 地址

**Comment by hzlzh** [comment]
@littlebaozi 已更新修复，请前往首页尝试。
