### ISSUE TITLE
SASS编译问题

### ISSUE THREAD

**Issue by ron0227** [weixin/WeFlow#82]
#### 运行环境：
- [x] 操作系统 & 版本： `Windows 10` 
- [x] WeFlow 版本： `v1.3.2`
#### 反馈具体描述：

![qq 20161007091257](https://cloud.githubusercontent.com/assets/14176408/19176012/7b827be4-8c6e-11e6-8503-c5510605da60.png)
![qq 20161007091302](https://cloud.githubusercontent.com/assets/14176408/19176015/7fa57618-8c6e-11e6-8070-6ae85a7f2530.png)
![qq 20161007091318](https://cloud.githubusercontent.com/assets/14176408/19176018/82cffa02-8c6e-11e6-9ed5-15b92af72042.png)

sass我每次修改被import的文件就会报错，说没有这个import文件，但是我保存多几次就又编译了，然后我去style-index.scss保存又没事了，很奇葩的一个问题

**Comment by xcsweb** [comment]
我用less的时候没有出现过这个问题

**Comment by littledu** [comment]
去掉你的变量试试
