### ISSUE TITLE
编译时卡住了，一直卡在compileHtml success这里没有下一步响应

### ISSUE THREAD

**Issue by licanbluesea** [weixin/WeFlow#83]
#### 运行环境

- [x] 操作系统 & 版本： `Windows 7 x64` 
- [x] WeFlow 版本： `v1.3.2`
- [x] node 版本： `v6.7.0`

#### 反馈具体描述：
在执行yo workflow命令和系统反馈npm install 之后，我强制退出来了，然后点击工具面板的开发，显示成功并打开网页，并且修改文件也是成功监听得到的。
但是在点击工具面板的编译，就是卡在了compileHtml success这一项，同时dist文件夹也没有出现。
如图：
![a57d6d0b-ac62-406b-bc52-30a5d32e325c](https://cloud.githubusercontent.com/assets/6637283/19218711/9be0a3cc-8e33-11e6-87ec-1053d0c149d5.png)

**Comment by xcsweb** [comment]
打开调试模式，估计是你的js报错了

**Comment by licanbluesea** [comment]
我后来把原来的删掉了，然后yo workflow一次。不过还是这样而且并没有改里面任何一个文件

**Comment by licanbluesea** [comment]
另外你说的调试模式，是怎么打开的？

**Comment by littledu** [comment]
@licanbluesea  yo workflow 跟这个 WeFlow 没有关系的，调试模式在 `窗口->调试模式`

**Comment by hzlzh** [comment]
@licanbluesea WeFlow 的环境依赖是在你下载软件之后已经 ok 的，所以你删除那个 test 的项目试一下默认 example 项目能否跑起来。

另外 `yo workflow` 这个命令是用来安装命令行版本的工作流使用的，参看这里：https://github.com/weixin/tmt-workflow
