### ISSUE TITLE
生产编译后，build.js生成的路径问题

### ISSUE THREAD

**Issue by catest** [weixin/WeFlow#86]
#### 运行环境

- [x] 操作系统 & 版本：`macOS (10.x.x)` 

#### 反馈具体描述：
html文件中关于js路径引用如下：

`
<script src="../js/other.js"></script>
<script src="../js/main.js"></script>
`

**生产编译后**
lib.js路径如下：
dist
-html
--js
---lib.js

**期望的正确lib.js路径如下：**
dist
-js
--lib.js

目前的情况是因为编译后的js路径并没有按照预期产生，会造成无法找到lib.js的bug

**Comment by littledu** [comment]
已知 bug，忙完这阵子来发一版

**Comment by ipengyo** [comment]
这么大的BUG 你们居然不修？
