### ISSUE TITLE
ftp上传时上传不成功而且没有任何提示

### ISSUE THREAD

**Issue by ZanderZhan** [weixin/WeFlow#89]
#### 运行环境
- [x] 操作系统 & 版本：`macOS (10.12.1)` 
- [x] WeFlow 版本： `v1.3.2`
#### 反馈具体描述：

ftp上传时上传不成功，一直提示 running ，配置项里面也没有端口号这一项配置。
![image](https://cloud.githubusercontent.com/assets/20698625/19799468/730725de-9d29-11e6-9cde-a54b22a9becd.png)
![image](https://cloud.githubusercontent.com/assets/20698625/19799489/8e6ee712-9d29-11e6-9c70-78cd62128753.png)

**Comment by littledu** [comment]
ftp默认端口21，确实没有给用户配置端口号的选项，mark一下。

**Comment by tomieric** [comment]
希望尽快发布，添加不了ftp端口号，根据文档在win10下找不到`.tmtworkflowrc` 文件不知如何修改

**Comment by littledu** [comment]
你配置了后，在项目目录下会有一个配置文件，里面有 ftp 的配置选项，你加一个 port 字段进去。
