### ISSUE TITLE
关于引入css库问题

### ISSUE THREAD

**Issue by sinceow** [weixin/WeFlow#9]
按 [之前的Issue](https://github.com/weixin/tmt-workflow/issues/37) 建议，将要引入的CSS改成LESS后缀再进行 import， 点「开发」都进不去监听模式了，对于CSS文件的支持有点问题

**Comment by sinceow** [comment]
解决了，不使用 import, 而是将所有的CSS文件都当成入口，换成 style-* 前缀，但还有个问题就是如果使用 Iconfont 那 fonts 字体文件应该放在什么位置?

**Comment by littledu** [comment]
用 LESS 的 `@import` 引入 css 模块文件，是可以监听的，你看看 log 面板是不是引入的 css 文件哪里报错了。

fonts 字体目前没有去具体分目录，在这里你需要把它们在 `media` 目录下，只有这个目录现在是对所有文件操作的。
