### ISSUE TITLE
点了开发按钮就一直Running。

### ISSUE THREAD

**Issue by w1997** [weixin/WeFlow#90]
#### 运行环境

- [x] 操作系统 & 版本：Windows10
- [x] WeFlow 版本： `v1.3.2`

#### 反馈具体描述：
![Uploading QQ图片20161101100424.png…]()

**Comment by luxiaowu** [comment]
<img src="http://a3.qpic.cn/psb?/V14SwqXB1UgZLi/kSPJAHUAD681dyGLjpLaS0FuKXS7cfeksd6EFRG0FLI!/b/dK0AAAAAAAAA&bo=aAFYAgAAAAADBxE!&rf=viewer_4">
上面的示例项目能watching...下面的不知为什么就不能在浏览器打开。刚开始是可以的
<img src="http://a1.qpic.cn/psb?/V14SwqXB1UgZLi/EGcJtFehY66kTS3dJKYLHuBdJs91TlydJ2nkfP3w6UA!/b/dLEAAAAAAAAA&bo=KAMSAgAAAAADAB4!&rf=viewer_4">

**Comment by littledu** [comment]
把那个css文件删掉试试
