### ISSUE TITLE
执行生产编译任务合并雪碧图时，怎么分组？

### ISSUE THREAD

**Issue by luxiaowu** [weixin/WeFlow#91]
#### 运行环境
- [x] 操作系统 & 版本：`Windows 10`  
- [x] WeFlow 版本： `v1.3.2`

#### 反馈具体描述：
- slice目录下的所有图片都合成在一张雪碧图上了，这张图片太大了。怎么才能分组合并，自动地限制雪碧图大小。
- 一个html文件引用多个 ‘style-xxx.less’ 文件就可以合成多张雪碧图了吗？

**Comment by hzlzh** [comment]
因为雪碧图名字是根据出口文件来定的，多个出口文件 `style-xxx.less` 可以来控制输出多张雪碧图。
