### ISSUE TITLE
我在src目录新建任何文件夹 dev目录和dist目录都没有任何显示

### ISSUE THREAD

**Issue by w1997** [weixin/WeFlow#93]
#### 运行环境

- [x] 操作系统 & 版本：Windows 10)

**Comment by hzlzh** [comment]
打开软件默认的 demo 编译呢，行不行

**Comment by w1997** [comment]
不行的，新建默认项目都出问题了，
![image](https://cloud.githubusercontent.com/assets/16370092/20089031/18d52e5a-a5bf-11e6-91c8-e055fd3da0c4.png)

**Comment by littledu** [comment]
使用姿势不对，src里面，只有 css,html,img,slice,js,media这几个目录有监听，在这几个里面新建文件或目录有效，其他都忽略。

**Comment by w1997** [comment]
好吧。
