### ISSUE TITLE
点编译，控制台无打印，按钮显示执行中，无dist目录生成。

### ISSUE THREAD

**Issue by luxiaowu** [weixin/WeFlow#94]
#### 运行环境

- [x] 操作系统 & 版本： `Windows 10`  
- [x] WeFlow 版本： `v1.3.2`

#### 反馈具体描述：

点开发可以成功监听，并生成 `dev` 目录。
但是点生产编译，控制台一句都不打印，也没有看到 `tmp` 目录生成。不报错，不知怎么检查？

**Comment by luxiaowu** [comment]
我明白了。
打开 `窗口` —— `调试模式` 在 `console` 界面就可以看到报错信息了。提示找不到雪碧图合成元素

**Comment by ipengyo** [comment]
一般这种情况报错了！
