### ISSUE TITLE
npm start 警告：kq_init: detected broken kqueue，导入项目没反应

### ISSUE THREAD

**Issue by jasonlam0619** [weixin/WeFlow#95]
正常 clone 并 `npm i` 后，运行 `npm start`，出现以下警告：
![image](https://cloud.githubusercontent.com/assets/8470477/20417739/8ed70446-ad82-11e6-99e0-34669aa95d21.png)

仍会弹出 Electron app，但导入项目没反应，无论是示例项目或自己项目。

**Comment by hzlzh** [comment]
尝试 `cnpm` https://npm.taobao.org/，看看是不是依赖没有拉取完整的问题
