### ISSUE TITLE
WeFlow 在特定情况下会卡死

### ISSUE THREAD

**Issue by zaxlct** [weixin/WeFlow#96]
- Mac OS 10.12.1 
我本地创建的项目，开发完成后。我复制了一下这个项目，换个名字。再用 WeFlow 打开，WeFlow 会卡死。

然后我卸载重新下载安装了，还是这样。

需要我把我本机上的这个项目压缩发给你们瞧瞧吗？

**Comment by littledu** [comment]
可以的，把项目打包一下发我： 410491325@qq.com

**Comment by zaxlct** [comment]
@littledu 
https://github.com/weixin/WeFlow/issues/97
是这个问题

**Comment by littledu** [comment]
好的，可以通过 窗口 - 调试模式，能更好的看到报错信息
