### ISSUE TITLE
雪碧图生成到sprite目录，但是朋友圈广告审核不过呢

### ISSUE THREAD

**Issue by anjorweb** [weixin/WeFlow#98]
#### 运行环境

- [x] 操作系统 & 版本：/`Windows7
- [x] WeFlow 版本： `v1.3.2`

#### 反馈具体描述：

是这样，使用合并雪碧图功能后，编译后，会把slice目录下所有图片合并sprite/index-sprite.png 这个目录文件，但是朋友圈广告审核那边，说dist.zip压缩包解压后不能存在html、css、img、slice、js、media以外的目录名，这该如何是好呢。。。生成的雪碧图偏偏是放到sprite目录下的。。

**Comment by hzlzh** [comment]
已经和相关同事同步过了，现在已经支持  sprite 目录的使用，如果还有其他问题随时反馈。
